### ISSUE TITLE
Can you write sample code to test on an arbitrary image?

### ISSUE THREAD

**Issue by aligoglos** [ZJULearning/ttfnet#1]
Please write demo code to how test `ttfnet` on image.

**Comment by liuzili97** [comment]
Hi, we add `ttfnet` to the `mmdetection` in this repository, and we do not plan to add more contents that are not related to the `ttfnet` itself.

Fortunately, the single-shot demo is supported in the official `mmdetection` =>[here](https://github.com/open-mmlab/mmdetection/blob/master/demo/inference_demo.ipynb)<=. You can have a try.

In addition, due to the bug in the latest `mmdetection`, we will not merge their latest commits into this repository until we believe that the `mmdetection` is stable enough.

**Comment by aligoglos** [comment]
thanks.
