### ISSUE TITLE
question about loss

### ISSUE THREAD

**Issue by chaos0625** [ZJULearning/ttfnet#10]
In this paper, loss is composed of hm loss and wh loss, why did you delete reg loss used in CenterNet?

**Comment by chaos0625** [comment]
If I add reg loss in ttfnet, can I get better performance?

**Comment by liuzili97** [comment]
In CenterNet, the offset of the center will cause the offset of the final prediction box. So one needs to add the offset to get better performance.
In TTFNet, instead of predicting the width and height of the object, we predict the distance from the center to the four sides of the box. So this is equivalent to integrating the offset into the regression. Adding offset is not needed.

**Comment by chaos0625** [comment]
> In CenterNet, the offset of the center will cause the offset of the final prediction box. So one needs to add the offset to get better performance.
> In TTFNet, instead of predicting the width and height of the object, we predict the distance from the center to the four sides of the box. So this is equivalent to integrating the offset into the regression. Adding offset is not needed.

**Comment by chaos0625** [comment]
thanks for you reply
