### ISSUE TITLE
About the stride in your paper

### ISSUE THREAD

**Issue by ghoshaw** [ZJULearning/ttfnet#5]
HI, in your paper, what is the parameter r? And you use xˆ1=ir−wˆls, yˆ1=jr−hˆts, to recover the bbox and enlarge the predicted results, means that your parameter r is big than 16?

**Comment by liuzili97** [comment]
Hi, `r` is the `wh_offset_base` in `ttf_head.py`, and it is set to `16`.

**Comment by liuzili97** [comment]
> N , C , H , W , r are batch size, number of categories, the height and width of the input image, and output stride.

`r` stands for the feature map stride, which is 4. We firstly map the `(i, j)` on feature map scale to the image scale `(ir, jr)`, then apply the enlarged predicted results `(w_ls, h_ts,w_rs,h_bs)`.

**Comment by ghoshaw** [comment]
so the ground truth w_l is (distance to the left edge of bbox for a point)/16 in image scale?

**Comment by liuzili97** [comment]
Since we use the IOU-based loss for regression, we can directly regress the decoded box(calculated by the formula) instead of the predicted results(i.e. the predicted w_l, h_t, w_r, h_b).

If you want to directly regress the predicted results(such as using l1 loss), you can set the ground truth w_l to be the (distance to the left edge of bbox for a point)/4 in image scale. However, we believe its a sub-optimal choice.

**Comment by ghoshaw** [comment]
ok, thanks very much!
